### ISSUE TITLE
cover image downloaded many times from CDN

### ISSUE THREAD

**Issue by lixas** [Idea-Software/SpotifyControls#7] opened 2019-08-12 12:46 UTC
I notices a problem, that album cover are downloaded many times from spotify CDN

> "*://*.scdn.co/*"

(on each UI refresh) while popup window is open and it makes significant amount of data to download.
Here is screenshot
![IMG1565613418](https://user-images.githubusercontent.com/2889604/62865683-ca73e080-bd17-11e9-9141-a420c32b19f2.png)

Maybe picture should be downloaded one time (on popup open) and changed after song changes?

**Comment by Sergej-Popov** [comment] 2019-09-14 17:12
I believe this is because you have cache disabled. Most likely by the dev tools. I have reproduced the issue with both dev tools & Fiddler:
![sc-no-cache-fiddler](https://user-images.githubusercontent.com/1652990/64911548-0f29d780-d71b-11e9-90aa-2596cfe0fc5b.gif)
Closing as not an issue.

**Closed as completed by Sergej-Popov** 2019-09-14 17:12 UTC
